name: damianlifecoach
favicon: null
layout_spectrum: 0.5990270785987377
typography_spectrum: 0.9595692409202456
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Personal Homepage
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#CFCFCF'
    - '#161616'
    - '#A3A3A3'
    - '#4B4B4B'
  brandStrength: 0.2765957
  lightness: 0.1123854438774288
  saturation: 0.6168069655541331
  rhythmicContrast: 0.9279199738521129
purpose: []
